# Dependencies
markdown:         kramdown
kramdown:
  extensions: ["tables"]

highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Deryk Makgill
tagline:          'Data Science, Apache Pig, Hadoop, Blogging, Tweets, Astrophysics'
site url: http://derykmakgill.com/vm
url: http://derykmakgill.com/vm


author:
  name:           'Deryk Makgill'
  url:            https://twitter.com/derykmakgill
paginate:         18

github:
  repo:           github.com/

# This is the list of pages to include in the header of the website.
pages_list:       
  Archive: '/archive/'
  
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50  

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
  - jekyll-paginate


